id: I7F0370A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:26:02+00:00'
last_modified: '2022-06-07T18:40:45.416234+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19223
  title: དཔལ་འབྲུག་པའི་ལུགས་ཀྱི་དབང་ཆོག་འདོད་རྒུའི་བང་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    09AC:
      image_group_id: I4159
      title: ''
      total_pages: 702
      order: 1
      base_file: 09AC.txt
    '1866':
      image_group_id: I4160
      title: ''
      total_pages: 584
      order: 2
      base_file: 1866.txt
    F7A6:
      image_group_id: I4161
      title: ''
      total_pages: 580
      order: 3
      base_file: F7A6.txt
    0D85:
      image_group_id: I4162
      title: ''
      total_pages: 574
      order: 4
      base_file: 0D85.txt
    CB15:
      image_group_id: I4163
      title: ''
      total_pages: 552
      order: 5
      base_file: CB15.txt
    5D56:
      image_group_id: I4164
      title: ''
      total_pages: 554
      order: 6
      base_file: 5D56.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
