id: I7F0370A0
legacy_id: P003255
ocr_import_info:
  bdrc_scan_id: W19223
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T04:21:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:16:49.506566+00:00'
last_modified: 2022-08-30 23:19:45.588439
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19223
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW19223
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབྲུག་པའི་ལུགས་ཀྱི་དབང་ཆོག་འདོད་རྒུའི་བང་མཛོད།
  author: འབྲུག་རྗེ་མཁན་པོ ༠༩་ཤཱཀྱ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.7818900311140337
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I4162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4162
      total_pages: 574
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4162.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.8040334186882897
    legacy_id: v004
  I4163:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4163
      total_pages: 552
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4163.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7924255284402631
    legacy_id: v005
  I4161:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4161
      total_pages: 580
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4161.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7973853577847794
    legacy_id: v003
  I4160:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4160
      total_pages: 584
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4160.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7980789656374301
    legacy_id: v002
  I4164:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4164
      total_pages: 554
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4164.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7823679118826197
    legacy_id: v006
  I4159:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4159
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4159.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.727811663782493
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
